### ISSUE TITLE
execute "run" first, and then execute "load" , that will throw error

### ISSUE THREAD

**Issue by alexqdjay** [timvieira/crf#9]
Traceback (most recent call last):
  File "crf/example.py", line 144, in <module>
    main()
  File "crf/example.py", line 138, in main
    run(proportion=[0.7, 0.3], load='model.pkl~')
  File "crf/example.py", line 104, in run
    validate(crf)
  File "crf/example.py", line 93, in validate
    llh = sum(map(crf.likelihood, iterview(train, msg='llh'))) / len(train)
  File "/crf/crf/crf.py", line 100, in likelihood
    (g0, g) = self.log_potentials(x)
  File "/crf/crf/crf.py", line 58, in log_potentials
    g0[y] = W[f[0,None,y]].sum()
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by TaoStarlit** [comment]
yes I am engage the same problem, I am using python 2.7

**Comment by timvieira** [comment]
Sorry. I just noticed this issue. Can you tell me what you passed in on the command line?
